import assert from 'node:assert/strict'
import { EventEmitter } from 'node:events'
import { PassThrough } from 'node:stream'
import { mkdtemp, mkdir, rm, writeFile, readFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import test from 'node:test'
import { createAgentPackageWithRuntime } from '../src/index.mjs'
const p={id:'p1',provider:'external',model:'arbitrary/model-name:latest',protocol:'openai-chat-completions',apiKeyEnv:'CREW_TEST_KEY',baseUrl:'http://127.0.0.1:9123/v1'}
function childFor(events,opts){const c=new EventEmitter();c.pid=0;c.exitCode=null;c.signalCode=null;c.stdin=new PassThrough();c.stdout=new PassThrough();c.stderr=new PassThrough();c.kill=()=>{c.signalCode='SIGTERM';c.exitCode=0;queueMicrotask(()=>c.emit('close',0,'SIGTERM'))};c.stdin.on('data',chunk=>{const r=JSON.parse(String(chunk));opts?.check?.(r,opts);queueMicrotask(async()=>{if(opts?.writeHistory){await mkdir(dirname(r.historyPath),{recursive:true});await writeFile(r.historyPath,JSON.stringify({scope:dirname(r.historyPath).split('/').at(-1),context:'stored native-task context'}))}for(const e of events)c.stdout.write(typeof e==='string'?e+'\n':JSON.stringify(e)+'\n');c.exitCode=opts?.exitCode??0;c.emit('close',c.exitCode,null)})});return c}
async function harness(t,events,opts={}){const d=await mkdtemp(join(tmpdir(),'crew-contract-'));t.after(()=>rm(d,{recursive:true,force:true}));let calls=0;const agent=await createAgentPackageWithRuntime({workspace:d,stateDir:join(d,'state'),env:{CREW_TEST_KEY:'private-key-abc',CREW_TEST_KEY_ALT:'alternate-private-key',OPENAI_API_KEY:'ambient-secret',NODE_OPTIONS:'--require=bad'}},{command:'fake-python',argsPrefix:['worker.py'],spawnProcess(_cmd,_args,spawnOpts){calls++;opts.spawnOpts=spawnOpts;return childFor(events,opts)}});return{d,agent,opts,get calls(){return calls}}}
const ok=[{type:'tool-call',name:'FileReadTool',callId:'c1',input:'x'},{type:'tool-result',name:'FileReadTool',callId:'c1',output:'contents'},{type:'assistant-delta',text:'done'},{type:'assistant-complete'}]
async function collect(iterator){const out=[];for await(const e of iterator)out.push(e);return out}
test('keeps full model ID, isolates child credentials, emits success terminal, and scopes persisted context',async t=>{const h=await harness(t,ok,{writeHistory:true,check:r=>{assert.equal(r.model.model,p.model);assert.equal(r.apiKeyEnv,p.apiKeyEnv);assert.equal('apiKey' in r,false)}});const events=await collect(h.agent.executeTask({taskId:'t1',sessionId:'s',input:'inspect',model:p}));assert.deepEqual(events.map(e=>e.type),['tool-call','tool-result','assistant-delta','assistant-complete']);const e=h.opts.spawnOpts.env;assert.equal(e.CREW_TEST_KEY,undefined);assert.equal(e.TALENT_CREWAI_API_KEY,'private-key-abc');assert.equal(e.OPENAI_API_KEY,undefined);assert.equal(e.NODE_OPTIONS,undefined);assert.equal(e.BROWSER,'/usr/bin/true');const {readdir}=await import('node:fs/promises');const scopes=await readdir(join(h.d,'state','profiles'));assert.equal(scopes.length,1);const history=JSON.parse(await readFile(join(h.d,'state','profiles',scopes[0],'history.json'),'utf8'));assert.match(history.context,/stored native-task context/)})
test('rejects invalid profile before starting worker',async t=>{const h=await harness(t,ok);assert.throws(()=>h.agent.executeTask({taskId:'x',input:'x',model:{...p,protocol:'unknown'}}),/profile/);assert.equal(h.calls,0)})
test('surfaces malformed output, missing terminal, and nonzero exit after terminal',async t=>{for(const [events,exit] of [[['not-json'],0],[[{type:'assistant-delta',text:'x'}],0],[[{type:'assistant-complete'}],2]]){const h=await harness(t,events,{exitCode:exit});const out=await collect(h.agent.executeTask({taskId:'x',input:'task',model:p}));assert.ok(out.some(e=>e.type==='error'))}})
test('separates session state for another profile and credential source',async t=>{const h=await harness(t,ok,{writeHistory:true});await collect(h.agent.executeTask({taskId:'one',sessionId:'same',input:'task',model:p}));await collect(h.agent.executeTask({taskId:'two',sessionId:'same',input:'task',model:{...p,apiKeyEnv:'CREW_TEST_KEY_ALT'}}));const {readdir}=await import('node:fs/promises');assert.equal((await readdir(join(h.d,'state','profiles'))).length,2)})
test('pre-aborted task does not spawn a worker and reports cancellation',async t=>{const h=await harness(t,ok);const aborter=new AbortController();aborter.abort();const out=await collect(h.agent.executeTask({taskId:'aborted',input:'task',model:p},{signal:aborter.signal}));assert.deepEqual(out,[{type:'cancelled'}]);assert.equal(h.calls,0)})
test('rejects malformed native tool events and redacts secrets from event metadata',async t=>{const h=await harness(t,[{type:'tool-call',name:'hide private-key-abc',callId:'private-key-abc',input:'private-key-abc'}]);const out=await collect(h.agent.executeTask({taskId:'bad',input:'task',model:p}));assert.ok(out.some(e=>e.type==='error'));const h2=await harness(t,[{type:'tool-call',name:'FileReadTool',callId:'c1',input:3}]);const out2=await collect(h2.agent.executeTask({taskId:'bad2',input:'task',model:p}));assert.ok(out2.some(e=>e.type==='error'))})
